-- ============================================================
-- A.S. Bologne - log notifiche WhatsApp automatiche
-- Data: 2026-06-30
--
-- Applicare questo file dopo 20260614_disponibilita_whatsapp.sql.
-- I token WhatsApp NON vanno nel database: devono essere segreti
-- della Edge Function Supabase.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS notifiche_whatsapp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id INTEGER REFERENCES matches(id) ON DELETE SET NULL,
  giocatore_id INTEGER REFERENCES giocatori(id) ON DELETE SET NULL,
  telefono TEXT,
  stato TEXT NOT NULL CHECK (stato IN ('inviato', 'errore', 'saltato')),
  dettaglio TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE notifiche_whatsapp ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "admin_manage_whatsapp_notifications" ON notifiche_whatsapp;
CREATE POLICY "admin_manage_whatsapp_notifications"
  ON notifiche_whatsapp
  FOR ALL
  TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

REVOKE ALL ON notifiche_whatsapp FROM anon;
GRANT SELECT, INSERT, DELETE ON notifiche_whatsapp TO authenticated;

COMMIT;
