-- ============================================================
-- A.S. Bologne - stagioni settembre/agosto e archivio automatico
-- Data: 2026-07-23
--
-- La nuova stagione viene creata in modo idempotente al primo accesso
-- al sito dopo il 1 settembre. Le partite e le statistiche precedenti
-- non vengono cancellate: restano collegate alla stagione conclusa.
-- ============================================================

BEGIN;

CREATE TABLE IF NOT EXISTS public.stagioni (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  anno_inizio INTEGER NOT NULL UNIQUE,
  codice TEXT NOT NULL UNIQUE,
  data_inizio DATE NOT NULL,
  data_fine DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT stagione_anno_valido CHECK (anno_inizio BETWEEN 2000 AND 2200),
  CONSTRAINT stagione_date_valide CHECK (
    data_inizio = make_date(anno_inizio, 9, 1)
    AND data_fine = make_date(anno_inizio + 1, 8, 31)
  ),
  CONSTRAINT stagione_codice_valido CHECK (
    codice = anno_inizio::TEXT || '/' || (anno_inizio + 1)::TEXT
  )
);

ALTER TABLE public.stagioni ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "read_all" ON public.stagioni;
CREATE POLICY "read_all"
  ON public.stagioni
  FOR SELECT
  TO anon, authenticated
  USING (TRUE);

DROP POLICY IF EXISTS "admin_manage_stagioni" ON public.stagioni;
CREATE POLICY "admin_manage_stagioni"
  ON public.stagioni
  FOR ALL
  TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

GRANT SELECT ON public.stagioni TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.stagioni TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.stagioni_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.anno_inizio_stagione(p_data DATE)
RETURNS INTEGER
LANGUAGE SQL
IMMUTABLE
STRICT
SET search_path = public, pg_temp
AS $$
  SELECT CASE
    WHEN EXTRACT(MONTH FROM p_data) >= 9
      THEN EXTRACT(YEAR FROM p_data)::INTEGER
    ELSE EXTRACT(YEAR FROM p_data)::INTEGER - 1
  END;
$$;

REVOKE ALL ON FUNCTION public.anno_inizio_stagione(DATE) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.anno_inizio_stagione(DATE)
  TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.crea_stagione_per_data(p_data DATE)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_anno INTEGER;
  v_id INTEGER;
BEGIN
  v_anno := public.anno_inizio_stagione(p_data);

  INSERT INTO public.stagioni (
    anno_inizio,
    codice,
    data_inizio,
    data_fine
  )
  VALUES (
    v_anno,
    v_anno::TEXT || '/' || (v_anno + 1)::TEXT,
    make_date(v_anno, 9, 1),
    make_date(v_anno + 1, 8, 31)
  )
  ON CONFLICT (anno_inizio)
  DO UPDATE SET anno_inizio = EXCLUDED.anno_inizio
  RETURNING id INTO v_id;

  RETURN v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.crea_stagione_per_data(DATE) FROM PUBLIC;

-- Crea le stagioni gia presenti nei dati storici e quella corrente.
INSERT INTO public.stagioni (
  anno_inizio,
  codice,
  data_inizio,
  data_fine
)
SELECT DISTINCT
  public.anno_inizio_stagione(m.data),
  public.anno_inizio_stagione(m.data)::TEXT
    || '/'
    || (public.anno_inizio_stagione(m.data) + 1)::TEXT,
  make_date(public.anno_inizio_stagione(m.data), 9, 1),
  make_date(public.anno_inizio_stagione(m.data) + 1, 8, 31)
FROM public.matches m
ON CONFLICT (anno_inizio) DO NOTHING;

SELECT public.crea_stagione_per_data(
  (NOW() AT TIME ZONE 'Europe/Rome')::DATE
);

ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS stagione_id INTEGER
    REFERENCES public.stagioni(id) ON DELETE RESTRICT;

UPDATE public.matches m
SET stagione_id = s.id
FROM public.stagioni s
WHERE m.stagione_id IS NULL
  AND m.data BETWEEN s.data_inizio AND s.data_fine;

ALTER TABLE public.matches
  ALTER COLUMN stagione_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_matches_stagione_id
  ON public.matches(stagione_id);

CREATE OR REPLACE FUNCTION public.assegna_stagione_partita()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  NEW.stagione_id := public.crea_stagione_per_data(NEW.data);
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.assegna_stagione_partita() FROM PUBLIC;

DROP TRIGGER IF EXISTS assegna_stagione_partita_trigger
  ON public.matches;
CREATE TRIGGER assegna_stagione_partita_trigger
BEFORE INSERT OR UPDATE OF data
ON public.matches
FOR EACH ROW
EXECUTE FUNCTION public.assegna_stagione_partita();

CREATE OR REPLACE FUNCTION public.assicura_stagione_corrente()
RETURNS SETOF public.stagioni
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_id INTEGER;
BEGIN
  v_id := public.crea_stagione_per_data(
    (NOW() AT TIME ZONE 'Europe/Rome')::DATE
  );

  RETURN QUERY
  SELECT s.*
  FROM public.stagioni s
  WHERE s.id = v_id;
END;
$$;

REVOKE ALL ON FUNCTION public.assicura_stagione_corrente() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.assicura_stagione_corrente()
  TO anon, authenticated;

NOTIFY pgrst, 'reload schema';

COMMIT;
